version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - QRaimbault
  assignees:
  - QRaimbault
  labels:
  - dependencies
  - chore
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: vue-eslint-parser
    versions:
    - 7.4.1
    - 7.5.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: vue-router
    versions:
    - 3.4.9
