language: node_js
sudo: required
os:
  - linux
node_js:
  - "9.11.2"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm install --depth 0 --silent
  - npm run lint